name : CML
on : [push]
jobs :
  run :
    runs-on : ubuntu-latest
    container : docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps :
      - uses : actions/checkout@v3
      - name : cml_run
        env : 
          repo_token : ${{ secrets.GITHUB_TOKEN }}
        run : |

          pip install -r requirements.txt
          python train.py

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          echo "![](./residuals.png)" >> report.md

          echo "## Data viz" >> report.md

          cml comment feature_importance.png >> report.md

          cml comment residuals.png >> report.md

          cml comment create report.md
